name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    name: Increment version
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: version
          value: ${{ steps.semver.outputs.nextStrict }}

      - name: Update app.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: app.json
          field: version
          value: ${{ steps.semver.outputs.nextStrict }}

      - name: Update IOS version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: app.json
          field: ios.buildNumber
          value: ${{ steps.semver.outputs.nextStrict }}

      - name: Get old versionCode for Android
        id: android_version_code
        uses: notiz-dev/github-action-json-property@release
        with:
          path: app.json
          prop_path: android.versionCode

      - name: Update Android versionCode
        uses: jossef/action-set-json-field@v2.1
        with:
          file: app.json
          field: android.versionCode
          value: $((${{ steps.android_version_code.outputs.prop }} + 1))

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: ğŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: ğŸ“¦ Install dependencies
        run: yarn install

      - name: ğŸš€ Build app
        run: eas build --non-interactive --platform all
