name: Main

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  main:
    name: Increment version
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v2

      - name: Get next version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master
          patchAll: true
          noVersionBumpBehavior: warn

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: ðŸ— Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Update versions
        run: node .github/scripts/set-versions.mjs ${{ steps.semver.outputs.nextStrict }}

      - name: ðŸ“¦ Install dependencies
        run: yarn install

      - name: ðŸš€ Build app
        run: |
          echo "${{ secrets.ASC_API_KEY }}" > apple-asc-api-key.p8
          eas build --non-interactive --platform all --auto-submit

      - name: Create and push tags
        run: |
          git config --local user.email "action@github.com.br"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore::bookmark: bump version to ${{ steps.semver.outputs.nextStrict }}"
          git push
          git tag -a ${{ steps.semver.outputs.nextStrict }} -m "Version ${{ steps.semver.outputs.nextStrict }}"
          git push --tags
